// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQs65kPa11KHapH-1jdMS8Sqw8kH7yQXU',
    appId: '1:558973694644:web:f9dbf321e2008750789de1',
    messagingSenderId: '558973694644',
    projectId: 'doctor-hunt16',
    authDomain: 'doctor-hunt16.firebaseapp.com',
    storageBucket: 'doctor-hunt16.firebasestorage.app',
    measurementId: 'G-KQVDHN1V1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfG6qYx87zc_9EnNt22-CkpCKWW_z8Y4',
    appId: '1:558973694644:android:8c608ebbe6a7a62a789de1',
    messagingSenderId: '558973694644',
    projectId: 'doctor-hunt16',
    storageBucket: 'doctor-hunt16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCetL6EYPokllj1OjtEMm9qdyP-g3PLtMo',
    appId: '1:558973694644:ios:9478ccef8597a695789de1',
    messagingSenderId: '558973694644',
    projectId: 'doctor-hunt16',
    storageBucket: 'doctor-hunt16.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );
}
